sudo: false
language: php
services: mongodb
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --no-interaction
  - wget https://scrutinizer-ci.com/ocular.phar
php:
  - 7.1
  - 7.2
matrix:
  allow_failures:
    - php: 7.2
script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - composer check
